/* global window */
//
// Centralised product catalogue. All 30 products across the 5 industries.
//
// Keyed as `${industrySlug}/${productSlug}`. The unified product.jsx looks
// up the entry from window.__INDUSTRY_SLUG + window.__PRODUCT_SLUG.
//
// NOTE: all spec values are drafts informed by typical industry standards.
// They MUST be reviewed by Liscarroll engineering before going live —
// some are conservative ranges, some are typical practice, none are tied
// to verified internal capability.
//

const PRODUCTS = {
  // =====================================================================
  // FARMING
  // =====================================================================
  "farming/milk-cooling-tanks": {
    industrySlug: "farming",
    industryName: "Farming",
    n: "01", of: "06",
    slug: "milk-cooling-tanks",
    name: "Milk Cooling Tanks",
    tagline: "Direct-expansion and ice-bank milk cooling for every herd size.",
    desc: "From a 1,000-litre tank for a single-herd setup to a full silo and buffer system for a co-op collection point, every Liscarroll milk cooling tank is engineered to exceed EN13732 and built from AISI 304 food-grade stainless steel. We have been building cooling tanks on this floor since 1973.",
    specs: [
      ["Capacity", "1,000 – 30,000 L"],
      ["Material", "AISI 304 stainless steel"],
      ["Standard", "EN13732 (exceeds)"],
      ["Cooling method", "Direct expansion or ice bank"],
      ["Internal finish", "Electropolished Ra ≤ 0.4μm"],
      ["Insulation", "100mm polyurethane foam"],
      ["CIP system", "Integrated spray-ball"],
      ["Connections", "IDF / DIN dairy fittings"],
    ],
    standaloneLabel: "PRODUCT · Milk cooling tank — standalone, polished",
    drawing1: "DRAWING · Front elevation — milk cooling tank",
    drawing2: "DRAWING · Side section — milk cooling tank",
    drawing3: "DRAWING · Plan view — milk cooling tank",
    installedLabel: "INSTALLED · Milk cooling tank, Co. Cork dairy farm",
    installedCaption: "1,200 L direct-expansion tank installed on a family dairy farm, Co. Cork.",
  },
  "farming/ice-builders": {
    industrySlug: "farming", industryName: "Farming", n: "02", of: "06",
    slug: "ice-builders",
    name: "Ice Builders",
    tagline: "Build ice on off-peak power. Deploy cooling on demand.",
    desc: "Ice builders accumulate cooling capacity overnight on off-peak electricity tariffs and discharge it during milking — reducing peak power draw and protecting milk quality without oversizing your refrigeration plant. Fabricated in AISI 304 stainless steel, compatible with all major cooling systems.",
    specs: [
      ["Ice storage", "500 – 10,000 kg equivalent"],
      ["Material", "AISI 304 stainless steel"],
      ["Refrigerant", "R449A (low-GWP HFO)"],
      ["Operation", "Overnight off-peak build"],
      ["Control", "PLC with remote monitoring"],
      ["Power supply", "3-phase 400V"],
      ["Insulation", "80mm polyurethane foam"],
      ["Connections", "IDF dairy fittings"],
    ],
    standaloneLabel: "PRODUCT · Ice builder unit — standalone",
    drawing1: "DRAWING · Front elevation — ice builder",
    drawing2: "DRAWING · Pipework schematic — ice builder",
    drawing3: "DRAWING · Electrical layout — ice builder",
    installedLabel: "INSTALLED · Ice builder, dairy co-op, Co. Kerry",
    installedCaption: "2,500 kg ice builder serving a 200-cow operation, Co. Kerry.",
  },
  "farming/milk-silos": {
    industrySlug: "farming", industryName: "Farming", n: "03", of: "06",
    slug: "milk-silos",
    name: "Milk Silos",
    tagline: "Large-volume vertical and horizontal milk storage for creameries and co-ops.",
    desc: "Liscarroll silos are engineered for creameries, co-op collection points and large-scale dairy operations. Available vertical or horizontal, fully insulated with automated CIP, and built to food-grade surface specifications. Capacities from 10,000 L to 200,000 L — larger on request.",
    specs: [
      ["Capacity", "10,000 – 200,000 L"],
      ["Material", "AISI 304 / 316L"],
      ["Orientation", "Vertical or horizontal"],
      ["Insulation", "100mm PU foam, cladded"],
      ["Agitation", "Tri-lobe rotary or paddle"],
      ["CIP", "Automated full-cycle spray"],
      ["Level", "Ultrasonic sender and display"],
      ["Access", "Top manway, side sample valve"],
    ],
    standaloneLabel: "PRODUCT · Milk silo — vertical, standalone",
    drawing1: "DRAWING · Vertical silo — front elevation",
    drawing2: "DRAWING · Silo — section view",
    drawing3: "DRAWING · Agitator detail — silo",
    installedLabel: "INSTALLED · Milk silo installation, creamery, Co. Cork",
    installedCaption: "50,000 L vertical silo installed at a co-op collection point, Co. Cork.",
  },
  "farming/buffer-tanks": {
    industrySlug: "farming", industryName: "Farming", n: "04", of: "06",
    slug: "buffer-tanks",
    name: "Buffer Tanks",
    tagline: "Smooth the flow between milking and bulk cooling.",
    desc: "Buffer tanks protect your cooling capacity by absorbing warm milk before it enters the main cooling system — critical for high-throughput parlours where cooling demand spikes at milking time. Every tank built to AISI 304 with a hygienically welded interior and integrated CIP circuit.",
    specs: [
      ["Capacity", "500 – 10,000 L"],
      ["Material", "AISI 304 stainless steel"],
      ["Internal finish", "Ra ≤ 0.8μm"],
      ["Insulation", "80mm polyurethane foam"],
      ["CIP system", "Spray-ball circuit"],
      ["Connections", "IDF / DIN dairy fittings"],
      ["Supports", "Adjustable stainless legs"],
      ["Working temp", "1 – 6°C"],
    ],
    standaloneLabel: "PRODUCT · Buffer tank — standalone, polished interior",
    drawing1: "DRAWING · Buffer tank — front elevation",
    drawing2: "DRAWING · Buffer tank — section view",
    drawing3: "DRAWING · Buffer tank — connections detail",
    installedLabel: "INSTALLED · Buffer tank, high-throughput parlour, Co. Tipperary",
    installedCaption: "3,000 L buffer tank serving a 300-cow rotary parlour, Co. Tipperary.",
  },
  "farming/heat-recovery-units": {
    industrySlug: "farming", industryName: "Farming", n: "05", of: "06",
    slug: "heat-recovery-units",
    name: "Heat Recovery Units",
    tagline: "Recover waste refrigeration heat. Cut water heating costs by up to 60%.",
    desc: "Heat recovery units capture waste heat from the condensing side of your refrigeration cycle and transfer it to your domestic hot water supply. Typically reduces water heating costs by 40–60%. Simple to retrofit alongside an existing cooling installation. Every unit CE-marked and built to specification.",
    specs: [
      ["Recovery efficiency", "40 – 60%"],
      ["Material", "AISI 304 plate pack"],
      ["Connections", "1.5\" – 2\" IDF"],
      ["Working pressure", "6 bar max"],
      ["Temp differential", "Up to 35°C"],
      ["Flow rate", "To project specification"],
      ["Certification", "CE marked"],
      ["Lead time", "4 – 6 weeks"],
    ],
    standaloneLabel: "PRODUCT · Heat recovery unit — standalone",
    drawing1: "DRAWING · Heat recovery — flow schematic",
    drawing2: "DRAWING · Plate pack — detail",
    drawing3: "DRAWING · Installation layout — heat recovery",
    installedLabel: "INSTALLED · Heat recovery unit, dairy farm, Co. Limerick",
    installedCaption: "Heat recovery unit recovering waste heat from two direct-expansion tanks, Co. Limerick.",
  },
  "farming/used-equipment": {
    industrySlug: "farming", industryName: "Farming", n: "06", of: "06",
    slug: "used-equipment",
    name: "Used Equipment",
    tagline: "Factory-reconditioned dairy equipment, re-certified and warranted.",
    desc: "We buy, strip, inspect and recondition used milk cooling tanks and ancillary dairy equipment at our Cork facility. Every piece is assessed against EN13732 and offered with a 12-month warranty. A cost-effective route to Liscarroll quality for smaller operations or temporary capacity.",
    specs: [
      ["Inspection", "Full strip-down and report"],
      ["Recertification", "EN13732 where applicable"],
      ["Warranty", "12 months parts and labour"],
      ["Lead time", "2 – 4 weeks from stock"],
      ["Tank range", "500 L – 50,000 L"],
      ["Condition grades", "Grade A or Grade B"],
      ["Documentation", "Full service history supplied"],
      ["Availability", "Subject to current stock"],
    ],
    standaloneLabel: "PRODUCT · Reconditioned milk tank — polished, ready to ship",
    drawing1: "DRAWING · Inspection report — used tank",
    drawing2: "DRAWING · Recondition checklist — standard",
    drawing3: "DRAWING · Certification documentation",
    installedLabel: "INSTALLED · Reconditioned tank, small dairy, Co. Cork",
    installedCaption: "Grade-A reconditioned 2,000 L tank, re-certified and installed, Co. Cork.",
  },

  // =====================================================================
  // FOOD & BEVERAGE
  // =====================================================================
  "food/production-lines": {
    industrySlug: "food", industryName: "Food & Beverage", n: "01", of: "06",
    slug: "production-lines",
    name: "Production Lines",
    tagline: "Full-bleed stainless production lines, designed and fabricated in-house.",
    desc: "From the receiving tank to the packing-line conveyor, we design and fabricate complete stainless steel production lines for butter producers, creameries and food exporters. Every line is laid out for cleanability first, throughput second — and every weld is hygienically finished and signed off before despatch.",
    specs: [
      ["Line length", "Up to 60 m continuous"],
      ["Material", "AISI 304 / 316L food-grade"],
      ["Internal finish", "Ra ≤ 0.8μm typical"],
      ["CIP system", "Integrated spray-ball, full automation"],
      ["Drainability", "Slope ≥ 1° on all horizontals"],
      ["Hygiene class", "EHEDG-aligned design"],
      ["Connections", "Tri-clamp, IDF or DIN to project"],
      ["Documentation", "MTR, weld map, surface report"],
    ],
    standaloneLabel: "PRODUCT · Production line — section, polished",
    drawing1: "DRAWING · Production line — plan view",
    drawing2: "DRAWING · Conveyor frame — section",
    drawing3: "DRAWING · CIP circuit — schematic",
    installedLabel: "INSTALLED · Production line, food brand, Co. Cork",
    installedCaption: "38-metre continuous production line installed at a major Irish food brand.",
  },
  "food/vessels-tanks": {
    industrySlug: "food", industryName: "Food & Beverage", n: "02", of: "06",
    slug: "vessels-tanks",
    name: "Vessels & Tanks",
    tagline: "Process vessels for food and beverage — jacketed, agitated, mirror-finished.",
    desc: "We fabricate process vessels and tanks for butter producers, breweries, dairies and exporters — jacketed for temperature control, agitated where the process needs it, and finished to the surface specification your QA function audits to. Capacities from 200 L pilot vessels to 50,000 L process tanks.",
    specs: [
      ["Capacity", "200 – 50,000 L"],
      ["Material", "AISI 304 / 316L"],
      ["Internal finish", "Ra ≤ 0.4 – 0.8μm to spec"],
      ["Jacket", "Half-pipe, dimple, or full"],
      ["Working pressure", "Atmospheric to 6 bar"],
      ["Agitation", "Top, side or bottom-entry"],
      ["CIP", "Integrated spray-ball"],
      ["Documentation", "MTR + pressure test certificate"],
    ],
    standaloneLabel: "PRODUCT · Process vessel — jacketed, polished",
    drawing1: "DRAWING · Process vessel — front elevation",
    drawing2: "DRAWING · Jacket detail — section",
    drawing3: "DRAWING · Agitator + drive — assembly",
    installedLabel: "INSTALLED · Jacketed vessel, creamery, Co. Cork",
    installedCaption: "8,000 L jacketed vessel installed at an Irish creamery for butter production.",
  },
  "food/conveyor-systems": {
    industrySlug: "food", industryName: "Food & Beverage", n: "03", of: "06",
    slug: "conveyor-systems",
    name: "Conveyor Systems",
    tagline: "Hygienic stainless steel conveyors for food production environments.",
    desc: "Open-frame stainless conveyors built for cleanability, with food-grade modular belts, sealed-bearing drive units and tool-less guard removal for hygiene access. Specified to your line layout and integrated with the surrounding stainless work where it matters.",
    specs: [
      ["Frame material", "AISI 304 box section"],
      ["Belt", "FDA / EU 10/2011 modular plastic"],
      ["Length", "Up to 30 m per run"],
      ["Width", "100 – 1,200 mm"],
      ["Speed", "Variable, 0.05 – 1.0 m/s"],
      ["Drive", "IP69K-rated geared motor"],
      ["Construction", "Open frame, fully washdown"],
      ["Guards", "Tool-less removable polycarbonate"],
    ],
    standaloneLabel: "PRODUCT · Conveyor — standalone, washdown frame",
    drawing1: "DRAWING · Conveyor — side elevation",
    drawing2: "DRAWING · Drive end — detail",
    drawing3: "DRAWING · Frame — section view",
    installedLabel: "INSTALLED · Conveyor system, packing line, Co. Limerick",
    installedCaption: "Three-stage conveyor system feeding a high-speed packing line at a food exporter.",
  },
  "food/cleanroom-fittings": {
    industrySlug: "food", industryName: "Food & Beverage", n: "04", of: "06",
    slug: "cleanroom-fittings",
    name: "Cleanroom Fittings",
    tagline: "Stainless fittings, brackets and hardware for hygienic environments.",
    desc: "Wall-flush brackets, sealed penetrations, hygienic doors and architectural stainless work for cleanroom and high-care food environments. Designed to the contamination-control standard your QA team needs and built to integrate cleanly with the surrounding fabric.",
    specs: [
      ["Material", "AISI 304 / 316L"],
      ["Surface finish", "2B, 4 brushed or mirror"],
      ["Fixings", "Hygienic, sealed M-bolt"],
      ["Edge prep", "Continuous radius, no flat seams"],
      ["Penetrations", "EPDM-sealed, IP65"],
      ["Compatibility", "Aligned with EHEDG / GFSI guidance"],
      ["Custom work", "To architect's specification"],
      ["Lead time", "3 – 6 weeks typical"],
    ],
    standaloneLabel: "PRODUCT · Cleanroom fitting — bracket assembly",
    drawing1: "DRAWING · Hygienic penetration — detail",
    drawing2: "DRAWING · Wall bracket — section",
    drawing3: "DRAWING · Door frame — assembly",
    installedLabel: "INSTALLED · Cleanroom fittings, ingredients plant, Co. Tipperary",
    installedCaption: "Bespoke cleanroom fittings installed across a high-care ingredients production area.",
  },
  "food/mixing-equipment": {
    industrySlug: "food", industryName: "Food & Beverage", n: "05", of: "06",
    slug: "mixing-equipment",
    name: "Mixing Equipment",
    tagline: "Top, side and bottom-entry mixers integrated into Liscarroll process tanks.",
    desc: "Mixing equipment specified, fabricated and integrated as part of a complete Liscarroll vessel build — agitator type, blade geometry, motor sizing and seal selection are all chosen to match your product viscosity and hygiene class.",
    specs: [
      ["Mixer type", "Top, side or bottom-entry"],
      ["Drive", "IP55 / IP65 geared motor"],
      ["Power", "0.37 – 30 kW typical"],
      ["Blade", "Anchor, propeller, paddle, dispersion"],
      ["Seal", "Single mech, double, dry-running"],
      ["CIP compatibility", "Yes — design to spec"],
      ["Material", "AISI 304 / 316L wetted parts"],
      ["Speed control", "VSD with HMI option"],
    ],
    standaloneLabel: "PRODUCT · Mixing equipment — top-entry assembly",
    drawing1: "DRAWING · Top-entry mixer — assembly",
    drawing2: "DRAWING · Seal arrangement — detail",
    drawing3: "DRAWING · Blade geometry — options",
    installedLabel: "INSTALLED · Mixing tank with top-entry agitator, Co. Cork",
    installedCaption: "5,000 L jacketed mixer with top-entry anchor agitator, Co. Cork creamery.",
  },
  "food/bespoke-process-lines": {
    industrySlug: "food", industryName: "Food & Beverage", n: "06", of: "06",
    slug: "bespoke-process-lines",
    name: "Bespoke Process Lines",
    tagline: "Outside the catalogue — start from a flow diagram, end with a working line.",
    desc: "When the off-the-shelf doesn't fit, we engineer from your process flow diagram up. Site survey, 3D layout, fabrication, FAT, install, commission. The full sequence, run by our project management team, with one accountable Liscarroll engineer from start to handover.",
    specs: [
      ["Scope", "P&ID through commissioning"],
      ["Survey", "On-site, in-person, included"],
      ["3D layout", "Issued for client review at concept"],
      ["FAT", "Performed at our Cork plant"],
      ["Install", "Liscarroll-led, sub-contracted disciplines"],
      ["Documentation", "Full ISO 9001 dossier"],
      ["Lead time", "Project-dependent — typical 12 – 28 wks"],
      ["Single point of contact", "One engineer, start to finish"],
    ],
    standaloneLabel: "PRODUCT · Bespoke process line — concept render",
    drawing1: "DRAWING · Flow schematic — example",
    drawing2: "DRAWING · 3D plant layout — section",
    drawing3: "DRAWING · Skid frame — assembly",
    installedLabel: "INSTALLED · Bespoke process line, food exporter, Co. Cork",
    installedCaption: "Complete bespoke process line, designed, built and commissioned for a Cork food exporter.",
  },

  // =====================================================================
  // PHARMACEUTICALS
  // =====================================================================
  "pharma/passivated-vessels": {
    industrySlug: "pharma", industryName: "Pharmaceuticals", n: "01", of: "06",
    slug: "passivated-vessels",
    name: "Passivated Vessels",
    tagline: "Passivated, electropolished pharmaceutical process vessels.",
    desc: "Pharmaceutical-grade process vessels in 316L, electropolished and passivated to your validation document. Surface roughness, weld map and material certificates are issued with every job — included as standard, not as a paid add-on.",
    specs: [
      ["Material", "AISI 316L (low-carbon)"],
      ["Surface finish", "Ra ≤ 0.4μm electropolished"],
      ["Passivation", "Citric or nitric, ASTM A967"],
      ["Welds", "Orbital, full-penetration, fully ground"],
      ["Capacity", "100 – 25,000 L"],
      ["Pressure", "Vacuum to 6 bar (higher on request)"],
      ["Documentation", "MTR, EP report, passivation cert"],
      ["Validation support", "IQ / OQ documentation included"],
    ],
    standaloneLabel: "PRODUCT · Passivated vessel — mirror polished",
    drawing1: "DRAWING · Passivated vessel — front elevation",
    drawing2: "DRAWING · Weld map — section",
    drawing3: "DRAWING · Internal finish — surface report",
    installedLabel: "INSTALLED · Passivated vessel, pharma client (NDA), Co. Cork",
    installedCaption: "316L passivated vessel installed at an Irish pharmaceutical site (under NDA).",
  },
  "pharma/sterile-pipework": {
    industrySlug: "pharma", industryName: "Pharmaceuticals", n: "02", of: "06",
    slug: "sterile-pipework",
    name: "Sterile Pipework",
    tagline: "Orbital-welded, fully drainable sterile pipework.",
    desc: "Sterile pipework fabricated in 316L tubing, joined with orbital welds, sloped for drainability and pressure-tested before despatch. Every joint logged, every weld sample retained, every coupon validated — your auditors get the documentation pack on day one.",
    specs: [
      ["Tubing", "AISI 316L, ASTM A270"],
      ["Welds", "Automated orbital, BPE-aligned"],
      ["Slope", "≥ 1% drainable"],
      ["Surface finish", "Ra ≤ 0.4μm wetted"],
      ["Coupons", "Sample weld retained per joint"],
      ["Pressure test", "Hydrotest to 1.5× working"],
      ["Cleanliness", "Pre-cleaned, capped on despatch"],
      ["Documentation", "Full BPE-style hand-over pack"],
    ],
    standaloneLabel: "PRODUCT · Sterile pipework — orbital welds",
    drawing1: "DRAWING · Pipework iso — section",
    drawing2: "DRAWING · Orbital weld — detail",
    drawing3: "DRAWING · Slope + drain detail",
    installedLabel: "INSTALLED · Sterile pipework, pharma site, Co. Dublin",
    installedCaption: "Sterile pipework run installed for a sterile fill / finish process, Co. Dublin.",
  },
  "pharma/mixing-tanks": {
    industrySlug: "pharma", industryName: "Pharmaceuticals", n: "03", of: "06",
    slug: "mixing-tanks",
    name: "Mixing Tanks",
    tagline: "GMP-grade mixing tanks with CIP and SIP capability.",
    desc: "Pharmaceutical mixing tanks — jacketed, agitated, electropolished, CIP/SIP-capable. Every tank built to your URS, with the validation documentation pack issued at handover.",
    specs: [
      ["Capacity", "200 – 15,000 L"],
      ["Material", "AISI 316L"],
      ["Internal finish", "Ra ≤ 0.4μm EP"],
      ["Jacket", "Dimple or half-pipe, 6 bar"],
      ["Agitation", "Top-entry, double mech seal"],
      ["CIP / SIP", "Spray-ball, steam to 134°C"],
      ["Validation", "IQ / OQ docs included"],
      ["Lead time", "10 – 16 wks typical"],
    ],
    standaloneLabel: "PRODUCT · GMP mixing tank — agitated, EP",
    drawing1: "DRAWING · Mixing tank — front elevation",
    drawing2: "DRAWING · Jacket + agitator — section",
    drawing3: "DRAWING · CIP / SIP circuit — schematic",
    installedLabel: "INSTALLED · GMP mixing tank, pharma client (NDA)",
    installedCaption: "5,000 L GMP-grade mixing tank installed at a pharmaceutical formulation suite.",
  },
  "pharma/gmp-surfaces": {
    industrySlug: "pharma", industryName: "Pharmaceuticals", n: "04", of: "06",
    slug: "gmp-surfaces",
    name: "GMP Surfaces",
    tagline: "GMP-compliant stainless surfaces for cleanrooms and process areas.",
    desc: "Wall panels, work-surface fabrications, hygienic ductwork and architectural stainless tailored for GMP environments. Continuous welds, ground and electropolished, with sealed penetrations sized for your services.",
    specs: [
      ["Material", "AISI 316L primarily"],
      ["Surface finish", "Ra ≤ 0.4μm typical"],
      ["Welds", "Continuous, ground and EP"],
      ["Edge prep", "Continuous radius — no flat seams"],
      ["Penetrations", "Sealed and validated"],
      ["Cleanability", "GMP / ISO 14644 aligned"],
      ["Documentation", "MTR + finish + roughness"],
      ["Lead time", "6 – 10 wks per phase"],
    ],
    standaloneLabel: "PRODUCT · GMP wall panel — EP finish",
    drawing1: "DRAWING · Wall panel — assembly",
    drawing2: "DRAWING · Penetration — sealed detail",
    drawing3: "DRAWING · Worktop — section",
    installedLabel: "INSTALLED · GMP surfaces, formulation suite (NDA)",
    installedCaption: "Full GMP wall and surface install for a formulation cleanroom (under NDA).",
  },
  "pharma/validation-documentation": {
    industrySlug: "pharma", industryName: "Pharmaceuticals", n: "05", of: "06",
    slug: "validation-documentation",
    name: "Validation Documentation",
    tagline: "Auditable documentation packs — included, not invoiced.",
    desc: "Material certificates, weld logs, surface roughness reports, passivation certs, IQ/OQ protocols, traceability matrices — bound, indexed and issued with every job. Built into the price, not a paid add-on.",
    specs: [
      ["Material certificates", "EN 10204 type 3.1"],
      ["Weld logs", "Per-joint, with welder ID"],
      ["Surface report", "Ra measured, multiple points"],
      ["Passivation cert", "Per ASTM A967"],
      ["IQ / OQ", "Protocols + signed-off records"],
      ["Traceability matrix", "URS → FDS → FAT linked"],
      ["Format", "PDF + bound hard copy"],
      ["Retention", "Held by Liscarroll for 10 years"],
    ],
    standaloneLabel: "PRODUCT · Validation pack — bound + indexed",
    drawing1: "DRAWING · Documentation index",
    drawing2: "DRAWING · Weld map — example",
    drawing3: "DRAWING · Traceability matrix — example",
    installedLabel: "DELIVERED · Validation pack, pharma client (NDA)",
    installedCaption: "Full validation pack delivered alongside the equipment for a Cork pharma client.",
  },
  "pharma/mirror-polished-finishes": {
    industrySlug: "pharma", industryName: "Pharmaceuticals", n: "06", of: "06",
    slug: "mirror-polished-finishes",
    name: "Mirror-Polished Finishes",
    tagline: "Sub-0.4μm mirror finishes for the highest-cleanability surfaces.",
    desc: "Mechanical polishing followed by electropolishing to bring critical surfaces below Ra 0.4μm — the spec that lets sterile media drain cleanly off your contact surfaces. Done in-house, measured, reported.",
    specs: [
      ["Surface", "Ra ≤ 0.2 – 0.4μm achievable"],
      ["Method", "Mechanical → EP → measure"],
      ["Coverage", "Internal + external (to spec)"],
      ["Measurement", "Profilometer, multiple points"],
      ["Report", "Per-vessel, signed off"],
      ["Materials", "AISI 316L primarily"],
      ["Re-polishing", "Available on existing vessels"],
      ["Lead time", "Add 1 – 2 wks to base build"],
    ],
    standaloneLabel: "PRODUCT · Mirror-polished vessel interior",
    drawing1: "DRAWING · Polishing process — flow",
    drawing2: "DRAWING · Surface measurement — points",
    drawing3: "DRAWING · Roughness report — example",
    installedLabel: "INSTALLED · Mirror-polished vessel, pharma client (NDA)",
    installedCaption: "Mirror-polished, electropolished vessel interior — Ra measured at 0.28μm typical.",
  },

  // =====================================================================
  // LEISURE
  // =====================================================================
  "leisure/plunge-pools": {
    industrySlug: "leisure", industryName: "Leisure", n: "01", of: "06",
    slug: "plunge-pools",
    name: "Plunge Pools",
    tagline: "Stainless steel plunge pools, polished to remove every visual seam.",
    desc: "Stainless steel plunge pools — bespoke dimensions, integrated water treatment, choice of finish. Stainless does not rot, does not stain, does not need replacing in a decade — which is why architects keep coming back.",
    specs: [
      ["Material", "AISI 316L marine grade"],
      ["Dimensions", "1.5 × 1.5 m up to 6 × 3 m"],
      ["Depth", "1.0 – 1.6 m typical"],
      ["Water treatment", "UV + low-chlorine integrated"],
      ["Heating", "Electric or heat-pump"],
      ["Finish", "Brushed, satin or mirror"],
      ["Cladding", "Optional timber or stone surround"],
      ["Lead time", "10 – 14 wks"],
    ],
    standaloneLabel: "PRODUCT · Stainless plunge pool — brushed",
    drawing1: "DRAWING · Plunge pool — plan view",
    drawing2: "DRAWING · Pool — section",
    drawing3: "DRAWING · Plant room — schematic",
    installedLabel: "INSTALLED · Plunge pool, wellness client, Co. Wicklow",
    installedCaption: "Brushed-finish plunge pool installed at a private wellness suite, Co. Wicklow.",
  },
  "leisure/hot-cold-tubs": {
    industrySlug: "leisure", industryName: "Leisure", n: "02", of: "06",
    slug: "hot-cold-tubs",
    name: "Hot & Cold Tubs",
    tagline: "Stainless contrast-therapy tubs — hot, cold and built to last.",
    desc: "Hot tubs and cold-plunge tubs in marine-grade stainless steel — engineered for the temperature extremes contrast therapy demands, with insulation, controls and water treatment integrated. A fixed installation that won't crack or stain like the polymer alternative.",
    specs: [
      ["Material", "AISI 316L"],
      ["Cold range", "3 – 12°C controllable"],
      ["Hot range", "35 – 42°C controllable"],
      ["Insulation", "Closed-cell PU foam, 60mm"],
      ["Controls", "Touch panel + remote monitoring"],
      ["Filtration", "Sand or cartridge, integrated"],
      ["Capacity", "1 – 4 person typical"],
      ["Surround", "Optional teak or stone"],
    ],
    standaloneLabel: "PRODUCT · Cold-plunge tub — brushed",
    drawing1: "DRAWING · Tub — front elevation",
    drawing2: "DRAWING · Tub — section",
    drawing3: "DRAWING · Equipment bay — layout",
    installedLabel: "INSTALLED · Hot + cold tub pair, wellness brand, Co. Cork",
    installedCaption: "Paired hot and cold tubs installed for a wellness brand at a Cork retreat centre.",
  },
  "leisure/spa-surrounds": {
    industrySlug: "leisure", industryName: "Leisure", n: "03", of: "06",
    slug: "spa-surrounds",
    name: "Spa Surrounds",
    tagline: "Stainless steel surrounds, channels and finishes for spa interiors.",
    desc: "Bespoke stainless work for spa interiors — drainage channels, wall cladding, water-feature housings, sauna stove surrounds. Designed alongside your architect, fabricated in Cork, polished to remove every visual seam before despatch.",
    specs: [
      ["Material", "AISI 316L marine grade"],
      ["Finish", "Brushed, satin, mirror or PVD"],
      ["Drainage channel", "Custom width, slot or grate"],
      ["Wall cladding", "Continuous-weld panels"],
      ["Sauna surrounds", "Heat-rated to 200°C"],
      ["Water features", "Integrated supply + drain"],
      ["Documentation", "MTR + finish report"],
      ["Lead time", "8 – 12 wks per phase"],
    ],
    standaloneLabel: "PRODUCT · Spa drainage channel — brushed",
    drawing1: "DRAWING · Drainage channel — section",
    drawing2: "DRAWING · Wall cladding — assembly",
    drawing3: "DRAWING · Sauna surround — detail",
    installedLabel: "INSTALLED · Spa surrounds, hotel spa, Co. Kerry",
    installedCaption: "Continuous-weld stainless cladding and channels installed at a five-star Kerry hotel spa.",
  },
  "leisure/wellness-suites": {
    industrySlug: "leisure", industryName: "Leisure", n: "04", of: "06",
    slug: "wellness-suites",
    name: "Wellness Suites",
    tagline: "Complete wellness installations — pool, plunge, sauna and surround.",
    desc: "End-to-end wellness suite delivery: plunge pool, hot tub, cold tub, integrated drainage, water treatment plant, sauna stove surrounds, wall cladding, finishes. One Liscarroll project manager, one stainless steel install, one handover.",
    specs: [
      ["Scope", "Survey to handover"],
      ["Disciplines", "Stainless fabrication + install"],
      ["Sub-trades", "Co-ordinated by Liscarroll"],
      ["Plant room", "Designed and integrated"],
      ["Materials", "AISI 316L throughout wetted parts"],
      ["Finishes", "Brushed, mirror or specified"],
      ["Project lead", "Single Liscarroll contact"],
      ["Lead time", "16 – 28 wks project-dependent"],
    ],
    standaloneLabel: "PRODUCT · Wellness suite — concept render",
    drawing1: "DRAWING · Suite plan — overview",
    drawing2: "DRAWING · Plant room — schematic",
    drawing3: "DRAWING · Sauna + plunge — detail",
    installedLabel: "INSTALLED · Wellness suite, retreat centre, Co. Wicklow",
    installedCaption: "Complete wellness suite — plunge, hot tub, cold tub, sauna surrounds — Co. Wicklow.",
  },
  "leisure/architectural-water-features": {
    industrySlug: "leisure", industryName: "Leisure", n: "05", of: "06",
    slug: "architectural-water-features",
    name: "Architectural Water Features",
    tagline: "Stainless steel water features for hospitality and public realm.",
    desc: "Architect-led water features in marine-grade stainless steel — wall waterfalls, reflecting pools, public-realm fountains. Designed for a 30-year service life with the polish that doesn't dull. We work to the architect's drawing.",
    specs: [
      ["Material", "AISI 316L marine grade"],
      ["Finish", "Brushed, mirror or PVD"],
      ["Water treatment", "UV + filtration integrated"],
      ["Lighting", "Integrated IP68 LED option"],
      ["Substructure", "Fully welded, weather-rated"],
      ["Installation", "On-site by Liscarroll team"],
      ["Documentation", "MTR + finish + commissioning"],
      ["Service life", "30+ years stainless"],
    ],
    standaloneLabel: "PRODUCT · Architectural water feature — wall fountain",
    drawing1: "DRAWING · Water feature — front elevation",
    drawing2: "DRAWING · Water feature — section",
    drawing3: "DRAWING · Lighting + plant — detail",
    installedLabel: "INSTALLED · Water feature, hotel atrium, Dublin",
    installedCaption: "5-metre wall waterfall installed in a Dublin hotel atrium, mirror finish.",
  },
  "leisure/custom-finishes": {
    industrySlug: "leisure", industryName: "Leisure", n: "06", of: "06",
    slug: "custom-finishes",
    name: "Custom Finishes",
    tagline: "Brushed, satin, mirror, PVD — finish to your architect's drawing.",
    desc: "Stainless steel takes whatever finish you specify. Brushed for the everyday spa surround, mirror for the architectural feature, PVD-coated rose gold or champagne for the hospitality fit-out. We finish in-house and we finish to spec.",
    specs: [
      ["Brushed", "#4 grain, 240 / 320 / 400"],
      ["Satin", "Glass-bead, low-glare"],
      ["Mirror", "#8 polish, Ra ≤ 0.05μm"],
      ["PVD coating", "Rose gold, champagne, black, bronze"],
      ["Electropolished", "Ra ≤ 0.4μm"],
      ["Patterning", "Bespoke etching available"],
      ["Sample service", "Pre-fab swatches at scale"],
      ["Lead time", "Add 1 – 3 wks to base build"],
    ],
    standaloneLabel: "PRODUCT · Custom finishes — sample card",
    drawing1: "DRAWING · Finish range — swatches",
    drawing2: "DRAWING · PVD process — schematic",
    drawing3: "DRAWING · Brushed grain — direction guide",
    installedLabel: "INSTALLED · PVD champagne fit-out, hospitality client",
    installedCaption: "PVD champagne-finish stainless detailing installed at a Dublin hospitality fit-out.",
  },

  // =====================================================================
  // BESPOKE
  // =====================================================================
  "bespoke/bar-installations": {
    industrySlug: "bespoke", industryName: "Bespoke", n: "01", of: "06",
    slug: "bar-installations",
    name: "Bar Installations",
    tagline: "Stainless bar fabrications — including signature work for Croke Park.",
    desc: "Bespoke bar fabrications for stadia, hospitality venues and high-traffic public spaces. The 'Tap. Take. Go.' bar installations at Croke Park were ours; so are quieter pieces in Dublin and Cork that we're not contractually allowed to name.",
    specs: [
      ["Material", "AISI 304 / 316L"],
      ["Finish", "Brushed, mirror or PVD"],
      ["Worktop spec", "Continuous-weld, ground flat"],
      ["Plumbing", "Integrated drinks lines + drain"],
      ["Refrigeration", "Built-in chiller bay option"],
      ["Lighting", "Concealed LED strip"],
      ["Modularity", "Standalone or run together"],
      ["Lead time", "8 – 14 wks"],
    ],
    standaloneLabel: "PRODUCT · Stadium bar fabrication — front",
    drawing1: "DRAWING · Bar — plan view",
    drawing2: "DRAWING · Bar — section",
    drawing3: "DRAWING · Plumbing + drinks line — detail",
    installedLabel: "INSTALLED · Stadium bar fabrication, Croke Park",
    installedCaption: "'Tap. Take. Go.' bar fabrication delivered for Croke Park, 2021.",
  },
  "bespoke/architectural": {
    industrySlug: "bespoke", industryName: "Bespoke", n: "02", of: "06",
    slug: "architectural",
    name: "Architectural",
    tagline: "Architectural stainless — facades, balustrades, structural detail.",
    desc: "Architect-led stainless steel work for new-build and refurbishment projects. Facade panels, balustrades, structural details, exposed welded steelwork. We work to your architect's drawing and we hit the build programme.",
    specs: [
      ["Material", "AISI 316L (external) / 304 (internal)"],
      ["Finish", "Brushed, mirror, PVD or patinated"],
      ["Welds", "Continuous, ground, dressed"],
      ["Tolerances", "± 0.5 mm on visual surfaces"],
      ["Site fixings", "Concealed, weather-rated"],
      ["Drawings", "Issued for review at GA + shop"],
      ["Site install", "Liscarroll-led"],
      ["Lead time", "10 – 20 wks per phase"],
    ],
    standaloneLabel: "PRODUCT · Architectural facade panel — brushed",
    drawing1: "DRAWING · Facade panel — assembly",
    drawing2: "DRAWING · Balustrade — section",
    drawing3: "DRAWING · Site-fixing detail",
    installedLabel: "INSTALLED · Architectural balustrade, Dublin office HQ",
    installedCaption: "Brushed stainless balustrade run installed at a Dublin office headquarters.",
  },
  "bespoke/sculpture": {
    industrySlug: "bespoke", industryName: "Bespoke", n: "03", of: "06",
    slug: "sculpture",
    name: "Sculpture",
    tagline: "Public-art sculpture in stainless steel, fabricated to artist's drawing.",
    desc: "We fabricate public-art sculpture from artist or studio drawings — full-form welding, ground and polished to remove every seam, weather-rated for outdoor placement, mounted to your structural engineer's specification.",
    specs: [
      ["Material", "AISI 316L marine grade"],
      ["Form", "From artist's 3D model"],
      ["Welding", "Continuous, ground invisible"],
      ["Finish", "Brushed, mirror, PVD or patinated"],
      ["Mounting", "To structural engineer's spec"],
      ["Weather rating", "30+ years marine"],
      ["Scale", "Sub-1m to 6m+ pieces"],
      ["Lead time", "12 – 24 wks per piece"],
    ],
    standaloneLabel: "PRODUCT · Public-art sculpture — mirror finish",
    drawing1: "DRAWING · Sculpture — fabrication drawing",
    drawing2: "DRAWING · Internal frame — section",
    drawing3: "DRAWING · Mounting — base detail",
    installedLabel: "INSTALLED · Public-art sculpture, civic project (NDA)",
    installedCaption: "4-metre stainless sculpture installed for an Irish civic public-art commission.",
  },
  "bespoke/one-offs": {
    industrySlug: "bespoke", industryName: "Bespoke", n: "04", of: "06",
    slug: "one-offs",
    name: "One-Offs",
    tagline: "If it can be drawn in stainless steel, we can make it.",
    desc: "The bracket nobody else will quote. The signage piece the architect wanted but no fabricator will commit to. The hospitality detail with one welder's name on it. Bring us a drawing or a sketch — we will engineer the rest.",
    specs: [
      ["Concept review", "Free at quotation stage"],
      ["Engineering", "We engineer from your sketch"],
      ["Material", "AISI 304 or 316L typical"],
      ["Finish", "Any — see Custom Finishes"],
      ["Quantity", "One — that is the point"],
      ["Tolerances", "Project-dependent"],
      ["Lead time", "4 – 12 wks typical"],
      ["Documentation", "MTR + finish report"],
    ],
    standaloneLabel: "PRODUCT · One-off fabrication — sketched, built",
    drawing1: "DRAWING · Sketch translated to spec",
    drawing2: "DRAWING · Fabrication drawing",
    drawing3: "DRAWING · Finish + assembly detail",
    installedLabel: "INSTALLED · One-off bespoke piece, hospitality client",
    installedCaption: "One-off bespoke stainless feature delivered to a Dublin hospitality fit-out.",
  },
  "bespoke/hospitality-fit-out": {
    industrySlug: "bespoke", industryName: "Bespoke", n: "05", of: "06",
    slug: "hospitality-fit-out",
    name: "Hospitality Fit-Out",
    tagline: "Stainless fit-out for hotels, restaurants and members' clubs.",
    desc: "Behind-bar work, kitchen pass fabrications, hostess stations, signage, balustrades — the stainless that makes the venue look right. Co-ordinated with your architect and your fit-out contractor, on the build programme.",
    specs: [
      ["Material", "AISI 304 / 316L"],
      ["Finish", "Brushed, satin, mirror, PVD"],
      ["Welds", "Continuous, ground, dressed"],
      ["Programming", "Co-ordinated with main contractor"],
      ["Site install", "By Liscarroll team"],
      ["Documentation", "MTR + finish + handover"],
      ["Aftercare", "Cleaning + re-polish guidance"],
      ["Lead time", "8 – 16 wks per phase"],
    ],
    standaloneLabel: "PRODUCT · Hospitality fit-out — bar pass",
    drawing1: "DRAWING · Pass — front elevation",
    drawing2: "DRAWING · Behind-bar — plan",
    drawing3: "DRAWING · Signage detail",
    installedLabel: "INSTALLED · Hotel hospitality fit-out, Dublin (NDA)",
    installedCaption: "Behind-bar and pass fit-out delivered for a Dublin five-star hotel (under NDA).",
  },
  "bespoke/public-realm": {
    industrySlug: "bespoke", industryName: "Bespoke", n: "06", of: "06",
    slug: "public-realm",
    name: "Public Realm",
    tagline: "Stainless street furniture, signage and public-realm fixtures.",
    desc: "Litter bins, bollards, bike racks, way-finding pylons, civic signage. Designed for a 25-year service life in the Irish weather, anti-vandal where it needs to be, marine-grade where it's coastal.",
    specs: [
      ["Material", "AISI 316L (coastal) / 304 (inland)"],
      ["Finish", "Brushed, satin or patinated"],
      ["Anti-vandal", "Tamper-proof fixings"],
      ["Service life", "25+ years"],
      ["Drainage", "Designed-in where required"],
      ["Replacement parts", "Stocked for 10 years"],
      ["Site install", "Liscarroll-led"],
      ["Lead time", "8 – 14 wks"],
    ],
    standaloneLabel: "PRODUCT · Public-realm bollard — brushed",
    drawing1: "DRAWING · Bollard — section",
    drawing2: "DRAWING · Way-finding pylon — assembly",
    drawing3: "DRAWING · Anti-vandal fixing — detail",
    installedLabel: "INSTALLED · Public-realm street furniture, civic project",
    installedCaption: "Stainless bollards and way-finding pylons installed for an Irish civic public-realm scheme.",
  },
};

// Order within each industry (used for prev/next navigation)
const PRODUCTS_BY_INDUSTRY = {};
for (const key of Object.keys(PRODUCTS)) {
  const p = PRODUCTS[key];
  if (!PRODUCTS_BY_INDUSTRY[p.industrySlug]) PRODUCTS_BY_INDUSTRY[p.industrySlug] = [];
  PRODUCTS_BY_INDUSTRY[p.industrySlug].push(p);
}

window.PRODUCTS = PRODUCTS;
window.PRODUCTS_BY_INDUSTRY = PRODUCTS_BY_INDUSTRY;
